version: '3.5'

services:
  users-db:
    container_name: users_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=users_db
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
volumes:
  postgres-data:
